name: Node.js Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Change to project directory
        run: cd Deema_Shopping_Mart-main

      - name: Install dependencies
        run: |
          cd Deema_Shopping_Mart-main
          npm install

      - name: Run Build
        run: |
          cd Deema_Shopping_Mart-main
          npm run build
